# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: socrates.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='socrates.proto',
  package='pb',
  syntax='proto3',
  serialized_options=b'Z(github.com/medelman17/socrates/server/pb',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0esocrates.proto\x12\x02pb\"5\n\x0fSocratesRequest\x12\x0f\n\x07passage\x18\x01 \x01(\t\x12\x11\n\tquestions\x18\x02 \x03(\t\"2\n\x0eSocratesAnswer\x12\x10\n\x08question\x18\x01 \x01(\t\x12\x0e\n\x06\x61nswer\x18\x02 \x01(\t\"7\n\x10SocratesResponse\x12#\n\x07\x61nswers\x18\x01 \x03(\x0b\x32\x12.pb.SocratesAnswer2>\n\x08Socrates\x12\x32\n\x03\x41sk\x12\x13.pb.SocratesRequest\x1a\x14.pb.SocratesResponse\"\x00\x42*Z(github.com/medelman17/socrates/server/pbb\x06proto3'
)




_SOCRATESREQUEST = _descriptor.Descriptor(
  name='SocratesRequest',
  full_name='pb.SocratesRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='passage', full_name='pb.SocratesRequest.passage', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='questions', full_name='pb.SocratesRequest.questions', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=75,
)


_SOCRATESANSWER = _descriptor.Descriptor(
  name='SocratesAnswer',
  full_name='pb.SocratesAnswer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='question', full_name='pb.SocratesAnswer.question', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='answer', full_name='pb.SocratesAnswer.answer', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=77,
  serialized_end=127,
)


_SOCRATESRESPONSE = _descriptor.Descriptor(
  name='SocratesResponse',
  full_name='pb.SocratesResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='answers', full_name='pb.SocratesResponse.answers', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=129,
  serialized_end=184,
)

_SOCRATESRESPONSE.fields_by_name['answers'].message_type = _SOCRATESANSWER
DESCRIPTOR.message_types_by_name['SocratesRequest'] = _SOCRATESREQUEST
DESCRIPTOR.message_types_by_name['SocratesAnswer'] = _SOCRATESANSWER
DESCRIPTOR.message_types_by_name['SocratesResponse'] = _SOCRATESRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SocratesRequest = _reflection.GeneratedProtocolMessageType('SocratesRequest', (_message.Message,), {
  'DESCRIPTOR' : _SOCRATESREQUEST,
  '__module__' : 'socrates_pb2'
  # @@protoc_insertion_point(class_scope:pb.SocratesRequest)
  })
_sym_db.RegisterMessage(SocratesRequest)

SocratesAnswer = _reflection.GeneratedProtocolMessageType('SocratesAnswer', (_message.Message,), {
  'DESCRIPTOR' : _SOCRATESANSWER,
  '__module__' : 'socrates_pb2'
  # @@protoc_insertion_point(class_scope:pb.SocratesAnswer)
  })
_sym_db.RegisterMessage(SocratesAnswer)

SocratesResponse = _reflection.GeneratedProtocolMessageType('SocratesResponse', (_message.Message,), {
  'DESCRIPTOR' : _SOCRATESRESPONSE,
  '__module__' : 'socrates_pb2'
  # @@protoc_insertion_point(class_scope:pb.SocratesResponse)
  })
_sym_db.RegisterMessage(SocratesResponse)


DESCRIPTOR._options = None

_SOCRATES = _descriptor.ServiceDescriptor(
  name='Socrates',
  full_name='pb.Socrates',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=186,
  serialized_end=248,
  methods=[
  _descriptor.MethodDescriptor(
    name='Ask',
    full_name='pb.Socrates.Ask',
    index=0,
    containing_service=None,
    input_type=_SOCRATESREQUEST,
    output_type=_SOCRATESRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SOCRATES)

DESCRIPTOR.services_by_name['Socrates'] = _SOCRATES

# @@protoc_insertion_point(module_scope)
